# Generated by Django 5.2.7 on 2025-11-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reading_time',
            field=models.IntegerField(default=0, help_text="Estimez le temps de lecture de l'article.", verbose_name='Temps de lecture (minutes)'),
        ),
        migrations.AddField(
            model_name='article',
            name='video_status',
            field=models.CharField(choices=[('NONE', 'Pas de video'), ('PLANNED', 'Video planifiee'), ('RECORDER', 'Video enregistree'), ('PUBLISHED', 'video publiee')], default='NONE', help_text='Indique si une video est associee ou prevue pour cet article.', max_length=10, verbose_name="statut video d'accompagnement"),
        ),
    ]
