# Generated by Django 5.2.7 on 2025-11-12 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Définissez la date/heure future pour une publication planifiée.', verbose_name='Date de publication'),
        ),
    ]
