# Generated by Django 5.2.7 on 2025-12-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name="Mis en avant sur la page d'accueil"),
        ),
    ]
