# Generated by Django 5.2.7 on 2025-10-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjetImage',
            new_name='ProjectImage',
        ),
    ]
