# Generated by Django 5.2.7 on 2026-01-09 23:45

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_rename_projetimage_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Guide du projet'),
        ),
    ]
